spring:
  h2:
    console:
      enabled: true

  jpa:
#    hibernate:
#      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql:true

  datasource:
    url: jdbc:h2:mem:testdb
    hikari:
      username: sa


server:
  port: 8090