spring:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql:true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


  datasource:
    url: jdbc:mysql://localhost:3306/book_manager
    username: root
    hikari:
      password:

  sql:
    init:
      mode: always


server:
  port: 8090